GET http://localhost:3333/products

###
POST http://localhost:3333/products
Content-Type: application/json

{
    "name": "Batata Frita",
    "price": 55.0
}

###
PUT http://localhost:3333/products/1
Content-Type: application/json

{
    "name": "Batata Frita",
    "price": 55.0
}